MangaLib/src/Web/Pages/CollectionPage.cshtml.cs
using Domain.Interfaces;
using Domain.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web.Pages
{
    public class CollectionPageModel : PageModel
    {
        private readonly IUserService _userService;

        //public List<Volume> Volumes { get; set; }
        public IEnumerable<Volume> Volumes { get; set; }


        public CollectionPageModel(IUserService userService)
        {
            _userService = userService;
        }

        public IActionResult OnGet()
        {
            User user = _userService.GetCurrentUser();

            if (user == null)
            {
                return RedirectToPage("/LoginPage");
            }

            Volumes = _userService.GetCollectionVolumes(user.Id);

            return Page();
        }
    }
}

MangaLib/src/Web/Pages/Home.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using Domain.Models;

namespace Web.Pages
{
    public class HomeModel : PageModel
    {
        public int? UserId { get; private set; }
        public string UserName { get; private set; }
        public string Email { get; set; }
        private readonly IHttpContextAccessor _httpContextAccessor;

        public HomeModel(/*IHttpContextAccessor httpContextAccessor*/)
        {
           // _httpContextAccessor = httpContextAccessor;
        }
        public void OnGet()
        {
            UserId = HttpContext.Session.GetInt32("UserId");
            UserName = HttpContext.Session.GetString("Username");
            Email = HttpContext.Session.GetString("Email");

            
        }
    }
}

MangaLib/src/Web/Pages/Index.cshtml.cs
using Domain.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace Web.Pages
{
    public class IndexModel : PageModel
    {
        private readonly HttpClient _httpClient;

        public List<User> Users { get; set; }

        public IndexModel(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        public async Task OnGetAsync()
        {
            var response = await _httpClient.GetAsync("https://localhost:7162/api/user");
            response.EnsureSuccessStatusCode();

            var content = await response.Content.ReadAsStringAsync();
            Users = JsonConvert.DeserializeObject<List<User>>(content);
        }
    }
}

MangaLib/src/Web/Pages/LicencePage.cshtml.cs
using Domain.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace Web.Pages
{
    public class LicencePageModel : PageModel
    {
        private readonly HttpClient _httpClient;

        public List<Licence> Licences { get; set; }

        public LicencePageModel(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        public async Task<IActionResult> OnGet()
        {
            var response = await _httpClient.GetAsync("https://localhost:7162/api/licence");
            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                Licences = JsonConvert.DeserializeObject<List<Licence>>(content);
                return Page();
            }
            else if (response.StatusCode == System.Net.HttpStatusCode.NotFound)
            {
                return NotFound();
            }
            else
            {
                return BadRequest();
            }
        }
    }
}

MangaLib/src/Web/Pages/VolumePage.cshtml.cs
using Domain.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Text;

namespace Web.Pages
{
    public class VolumePageModel : PageModel
    {
        private readonly HttpClient _httpClient;
        public Licence Licence { get; set; }
        public List<Volume> Volumes { get; set; }
        public VolumePageModel(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        public async Task<IActionResult> OnGet(int licenceId)
        {
            var licenceResponse = await _httpClient.GetAsync($"https://localhost:7162/api/licence/{licenceId}");
            if (!licenceResponse.IsSuccessStatusCode)
            {
                return NotFound();
            }

            var licenceContent = await licenceResponse.Content.ReadAsStringAsync();
            Licence = JsonConvert.DeserializeObject<Licence>(licenceContent);

            var volumeResponse = await _httpClient.GetAsync($"https://localhost:7162/api/licence/{licenceId}/volumes");
            if (volumeResponse.IsSuccessStatusCode)
            {
                var volumeContent = await volumeResponse.Content.ReadAsStringAsync();
                var volumeObject = JsonConvert.DeserializeObject<Volume>(volumeContent);
                Volumes = new List<Volume> { volumeObject };
            }

            return Page();
        }
        public async Task<IActionResult> OnPostAddToCollection(int volumeId)
        {
            var userId = 1;

            var volumeResponse = await _httpClient.GetAsync($"https://localhost:7162/api/volume/{volumeId}");
            if (!volumeResponse.IsSuccessStatusCode)
            {
                return NotFound();
            }

            var owner = new Owner { UserId = userId, VolumeId = volumeId };
            var json = JsonConvert.SerializeObject(owner);
            var content = new StringContent(json, Encoding.UTF8, "application/json");

            var addToCollectionResponse = await _httpClient.PostAsync("https://localhost:7162/api/user/collection", content);
            if (!addToCollectionResponse.IsSuccessStatusCode)
            {
                return BadRequest();
            }

            return RedirectToPage("/Collection");
        }
    }
}

MangaLib/src/Web/Pages/CollectionPage.cshtml
@page
@model Web.Pages.CollectionPageModel
@{
    ViewData["Title"] = "Ma collection";
}

<h1>Ma collection</h1>

@if (Model.Volumes != null && Model.Volumes.Any())
{
    <ul>
        @foreach (var volume in Model.Volumes)
        {
            <li>
                <h3>@volume.Title</h3>
                <p>Volume @volume.Number</p>
                <p>Pages: @volume.Pages</p>
                <p>Released: @volume.Released</p>
                @if (!string.IsNullOrEmpty(volume.Image))
                {
                    <img src="@volume.Image" alt="Volume Image" />
                }
                else
                {
                    <p>Pas d'image disponible</p>
                }
            </li>
        }
    </ul>
}
else
{
    <p>Votre collection est vide.</p>
}

MangaLib/src/Web/Pages/Home.cshtml
@page
@using Domain.Models;
@using Microsoft.AspNetCore.Identity
@model Web.Pages.HomeModel
@inject IHttpContextAccessor HttpContextAccessor

@{
}

<h1>@HttpContext.Request.Cookies["CurrentUser"];</h1>

@if (Model.UserId != null)
{
    <p>Welcome, User ID: @Model.UserId, Username: @Model.UserName</p>
}
else
{
    <h1>@Model.Email</h1>
    <h1>@HttpContext.Request.Cookies["CurrentUser"];</h1>
    <h1>@HttpContext.Session.GetString("Username");</h1>
    <p>You are not logged in.</p>
}

MangaLib/src/Web/Pages/Index.cshtml
@page
@model Web.Pages.IndexModel
@{
    ViewData["Title"] = "Accueil";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}


<h1>@ViewData["Title"]</h1>

<table>
    <thead>
        <tr>
            <th>Nom</th>
            <th>Email</th>
            <th>Âge</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model.Users)
        {
            <tr>
                <td>@user.Username</td>
                <td>@user.Email</td>
                <td>@user.Password</td>
            </tr>
        }
    </tbody>
</table>

<form method="get">
    <button type="submit">Obtenir les utilisateurs</button>
</form>

MangaLib/src/Web/Pages/LicencePage.cshtml
@page "/licence"
@model Web.Pages.LicencePageModel
@{
    ViewData["Title"] = "Licences";
}

<h1>Licences</h1>

@if (Model.Licences != null && Model.Licences.Any())
{
    <ul>
        @foreach (var licence in Model.Licences)
        {
            <li>
                <h3>@licence.Name</h3>
                @if (!string.IsNullOrEmpty(licence.Image))
                {
                    <img src="@licence.Image" alt="@licence.Name" />
                }
                else
                {
                    <p>No image available</p>
                }
                <a href="/licence/@licence.Id/volume">View Volumes</a>
            </li>
        }
    </ul>
}
else
{
    <p>Aucune licence trouvée.</p>
}

MangaLib/src/Web/Pages/LoginPage.cshtml
@page
@model Web.Pages.LoginPageModel
@{
    ViewData["Title"] = "Connexion";
}

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h1>@ViewData["Title"]</h1>

@if (Model.ErrorMessage != null)
{
    <p>@Model.ErrorMessage</p>
}

<form method="post">
    <div>
        <label for="username">Username:</label>
        <input asp-for="@Model.Username" id="username" type="text" required />
    </div>
    <div>
        <label for="password">Password:</label>
        <input asp-for="@Model.Password" id="password" type="password" required />
    </div>
    <div>
        <button type="submit" asp-page-handler="OnPostAsync">Login</button>
    </div>
</form>

MangaLib/src/Web/Pages/VolumePage.cshtml
@page "/licence/{licenceId:int}/volume"
@model Web.Pages.VolumePageModel
@{
    ViewData["Title"] = "Volumes";
}

<h1>Volumes</h1>

@if (Model.Licence != null)
{
    <h2>Licence: @Model.Licence.Name</h2>
}
else
{
    <p>Pas de licence trouvé</p>
}

@if (Model.Volumes != null && Model.Volumes.Any())
{
    <ul>
        @foreach (var volume in Model.Volumes)
        {
            <li>
                <h3>Volume @volume.Number - @volume.Title</h3>
                <p>Pages: @volume.Pages</p>
                <p>Released: @volume.Released</p>
                @if (!string.IsNullOrEmpty(volume.Image))
                {
                    <img src="@volume.Image" alt="Volume Image"/>
                }
                else
                {
                    <p>Pas d'image disponible</p>
                }
                <a href="/licence/@Model.Licence.Id/volume/@volume.Id">Voir les détails</a>

                <form method="post" asp-page-handler="AddToCollection" asp-route-volumeId="@volume.Id">
                    <button type="submit">Ajouter à ma collection</button>
                </form>
            </li>
        }
    </ul>
}
else
{
    <p>Pas de volume trouvé</p>
}